name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build static content
        run: |
          # Ensure slides.html exists in the root directory
          ls -l slides.html  # Check if the file is available

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: slides.html # Point to the single file

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4